#define TT_ATTRIBUTE_API __attribute__ ((visibility("hidden")))
#define TT_ATTRIBUTE_INNER __attribute__ ((visibility("hidden")))

#include "cppsrc/decoder/avcodec.cpp"
#include "cppsrc/decoder/jpeg.cpp"
#include "cppsrc/decoder/openh264.cpp"
#include "cppsrc/decoder/opus.cpp"
#include "cppsrc/decoder/png.cpp"
#include "cppsrc/decoder/speex.cpp"
#include "cppsrc/decoder/theora.cpp"
#include "cppsrc/decoder/vorbis.cpp"
#include "cppsrc/decoder.cpp"
#include "cppsrc/encoder/fdkaac.cpp"
#include "cppsrc/encoder/jpeg.cpp"
#include "cppsrc/encoder/openh264.cpp"
#include "cppsrc/encoder/opus.cpp"
#include "cppsrc/encoder/speex.cpp"
#include "cppsrc/encoder/theora.cpp"
#include "cppsrc/encoder/vorbis.cpp"
#include "cppsrc/encoder/x264.cpp"
#include "cppsrc/encoder/x265.cpp"
#include "cppsrc/encoder.cpp"
#include "cppsrc/resampler/audio.cpp"
#include "cppsrc/resampler/image.cpp"
#include "cppsrc/resampler/libyuv.cpp"
#include "cppsrc/resampler/resize.cpp"
#include "cppsrc/resampler/soundtouch.cpp"
#include "cppsrc/resampler/speexdsp.cpp"
#include "cppsrc/resampler/swresample.cpp"
#include "cppsrc/resampler/swscale.cpp"
#include "cppsrc/resampler.cpp"
#include "cppsrc/frame.cpp"
#include "cppsrc/reader.cpp"
#include "cppsrc/writer.cpp"
#include "cppsrc/util.cpp"
